### PR TITLE
fix: PR merge for CI systems using Checks API

### PR DESCRIPTION
**Pull request by jashandeep-sohi**
Issue
-----

Github Actions Workflows use the Checks API, as opposed to the Statues API, to post the status of a Workflow.

Current behavior of using the `/repos/{owner}/{repo}/statuses/{sha}` API to check if a PR is ready to be merged naturally only works for CI systems that use the Statues API (Jenkins?). One hack for GH Actions Workflows is to have a step that posts to the Statuses API, but that gets pretty tiresome after the second workflow.

Right now octopilot also needs read-only repository **admin** permissions to be able to `GET /repos/{owner}/{repo}/branches/{branch}/protection/required_status_checks` for a list of required status checks configured as part of the branch protection rules.

Fix
---

Use the PR `mergeable_state` field to determine when a PR is ready to be merged. This field is not documented very well, but a value of `clean` *should* mean all branch protection rules are satisfied.
This should cover both the Statues API & Checks API. Added bonus is any other branch protection rules (e.g. required approvals). Also, reduces the scope of the permissions needed.

### CODE REVIEW

**Review by vbehar — APPROVED** [review]

**Comment by MPV** [comment]
@jashandeep-sohi Thank you for this! Solves exactly the problem I saw/explained over at:
- https://github.com/dailymotion-oss/octopilot/issues/280#issuecomment-1818470120

I'll see if I can give this a try at some point.

**Comment by jashandeep-sohi** [comment]
Let us know how it goes. I did run some tests on a test repo.

I also have a patch for the auto-merge feature, but didn't want to conflate
the two. I'm thinking both methods should be available, with the auto-merge
one being opt-in. That method can also be asynchronous, i.e. you don't have
to wait around for the checks to pass. GitHub will do it for you.

**Comment by vbehar** [comment]
yep exactly, I totally agree with you. Feel free to share your other patch if you want to discuss it.
and thanks again for your contributions!

**Comment by MPV** [comment]
FYI: I raised #293, as this change broke `--pr-merge` for us.

**Pull request merged**
